import React from 'react';

const AdminSystem = () => {
  return ( 
    <div>
    <h1>System</h1>
    <p>Wafer topping cotton candy jelly beans cookie. Lemon drops macaroon pie. Dessert sweet apple pie pudding gummi bears lollipop tiramisu sugar plum. Marshmallow powder chocolate cake dessert biscuit biscuit. Biscuit cake ice cream dragée dragée tiramisu lollipop cake. Icing candy bear claw jelly sugar plum. Ice cream sweet roll dessert donut oat cake icing sugar plum topping. Cookie wafer gummies lemon drops toffee dragée lemon drops. Apple pie donut tootsie roll jelly. Macaroon brownie lemon drops chocolate marshmallow gingerbread pastry. Danish jelly gingerbread tart cake. Croissant tootsie roll cupcake jelly-o cotton candy.</p>
    <p>Pudding cake sweet topping muffin. Sesame snaps jujubes fruitcake soufflé tiramisu danish candy canes caramels brownie. Marshmallow marzipan bear claw croissant gummi bears sesame snaps. Jelly-o chupa chups gingerbread fruitcake tiramisu sweet chocolate. Liquorice biscuit ice cream candy canes. Cupcake donut liquorice soufflé oat cake cake. Sweet apple pie macaroon. Icing croissant brownie cookie sugar plum tart. Carrot cake pastry chupa chups tiramisu pudding jelly. Fruitcake topping danish chocolate marzipan donut. Apple pie powder chocolate bar cake jujubes cheesecake chocolate bar. Sugar plum dessert candy canes jelly.</p>
    <p>Carrot cake lemon drops pie oat cake. Sugar plum chocolate jelly beans. Pudding jelly-o muffin jelly sweet roll. Wafer fruitcake bear claw soufflé tootsie roll oat cake pie biscuit. Ice cream chocolate sweet donut powder fruitcake ice cream. Tootsie roll gummies tart gummies jelly beans cotton candy sugar plum jelly beans tart. Lemon drops jujubes cake cake sweet toffee sesame snaps pudding cotton candy. Toffee icing jelly-o. Wafer danish bear claw cookie cake pudding toffee. Soufflé tart icing candy cake. Topping pie cheesecake cookie bonbon gingerbread cupcake. Brownie gummi bears carrot cake chocolate cake lollipop liquorice lemon drops cupcake. Topping wafer chocolate sweet roll powder croissant lollipop marshmallow. Marzipan fruitcake chocolate cake bonbon bonbon.</p>
    <p>Cake donut sweet cookie chocolate croissant apple pie pastry. Carrot cake oat cake fruitcake cookie donut jelly beans tiramisu pie caramels. Powder biscuit chocolate bar cake cake. Candy canes cake bonbon wafer. Pudding apple pie sugar plum lollipop cake cupcake halvah apple pie brownie. Powder soufflé gingerbread. Powder caramels muffin carrot cake chocolate cake. Chupa chups jelly tootsie roll sweet roll jelly-o jelly. Toffee muffin sweet roll. Powder icing chocolate bar sesame snaps gingerbread toffee chocolate cake toffee caramels. Pastry muffin marshmallow dragée marshmallow topping cupcake. Biscuit liquorice liquorice pie chocolate bar tart lemon drops tiramisu sweet roll.</p>
    <p>Donut danish sweet cheesecake tiramisu. Pudding ice cream danish dessert. Biscuit croissant jujubes. Topping ice cream croissant gummies donut cake jujubes biscuit icing. Oat cake halvah ice cream pudding. Tiramisu oat cake jelly beans gummi bears cake jujubes donut. Soufflé sugar plum marzipan chocolate cake ice cream cheesecake chocolate bar lollipop. Croissant cotton candy sugar plum jujubes cotton candy sweet roll. Lemon drops cheesecake lemon drops macaroon pudding pudding marshmallow danish. Sweet caramels chupa chups. Chocolate toffee lollipop cookie jelly beans. Chocolate cake pie jelly apple pie gingerbread jelly beans jelly beans caramels. Icing carrot cake pie tiramisu. Tootsie roll candy apple pie pudding wafer.</p>
  </div>
  );
}

export default AdminSystem;
